[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MPL-2.0",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "Unlicense",
    "Zlib",
    "OpenSSL",
]
unlicensed-policy = "allow"

[advisories]
ignore = [
    "RUSTSEC-2026-0119",
    "RUSTSEC-2024-0437",
    "RUSTSEC-2025-0009",
    "RUSTSEC-2026-0099",
    "RUSTSEC-2026-0098",
    "RUSTSEC-2026-0104",
    "RUSTSEC-2026-0086",
    "RUSTSEC-2026-0089",
    "RUSTSEC-2026-0094",
    "RUSTSEC-2026-0095",
    "RUSTSEC-2026-0096",
    "RUSTSEC-2026-0088",
]
